### ISSUE TITLE
Absolute includes

### ISSUE THREAD

**Issue by hanno-jonlay** [MathiasPaumgarten/grunt-bake#6]
I guess this is more a personal preference, but it might be handy to be able to set include paths that were a bit more portable:

My terminology most likely sucks, but here's a quick stab! Maybe an include_base_path as a config option. I've been keeping all my source templates in a dir called 'partials'

```
bake:
  options:
    include_base_path: partials
  build:
    files:
      "dist/index.html": "partials/index.html"
```

And then that would allow you to do this:

```
<!--(bake /includes/nav.html)-->
```

Which would automatically take `/partials` as the starting point for any includes? That way you could repeat the same code snippet for the header of every page, regardless of whether you're keeping it in a subdirectory structure.

Even just being able to define a path relative to the Gruntfile would do the trick, and possibly be a fair bit easier. So: `/partials/includes/nav.html`

Obviously feel free to disregard if it doesn't fit where you want to take the plugin :smiley: Sorry for not being able to send you a more useful pull request - I'm not quite up to scratch on building the stuff, yet!
